WIP: Allow setting custom exit code on Mix error
elixir-lang/elixir pull request #10463
Opened 2020-10-29 15:53 UTC by hauleth

It is sometimes useful and desirable to have different exit code on
different errors (for example 1 on server error, 2 on connection error,
and so on). This change adds new field to the `Mix.Error` exception -
`code` that will be then used as an exit code value.

2020-10-29 16:03 UTC, josevalim commented on lib/mix/lib/mix.ex
> +    Kernel.raise(Mix.Error, mix: true, message: message, code: code)
I wonder if we should instead repurpose the `:mix` key. Something like this:

  def raise(message, opts \\ []) when is_binary(message) do
    Kernel.raise(Mix.Error, mix: Keyword.get(opts, :exit_code, 1), message: message)

And in the CLI, we check if mix is set. `true` is the same as 1.

2020-10-31 08:35 UTC, josevalim commented on lib/mix/test/mix/cli_test.exs
> +    end)
Those tests are very expensive so I think we are being too extensive in our coverage. I think a simple test that raises a custom code, such as `13` or whatever, should be enough.

2020-10-31 08:35 UTC, josevalim commented on lib/mix/lib/mix.ex
> +    Kernel.raise(Mix.Error, mix: Keyword.get(opts, :code, 1), message: message)
Can we please name `exit_code` for clarity? Also please update the function docs.

2020-10-31 13:01 UTC, eksperimental requested changes

2020-11-11 15:02 UTC, josevalim commented on lib/mix/lib/mix.ex
> +    Kernel.raise(Mix.Error, mix: Keyword.get(opts, :code, 1), message: message)
Ping! :)

2020-11-17 00:15 UTC, hauleth commented on lib/mix/lib/mix/cli.ex
> +    mod = name |> Module.split() |> Enum.at(0, "Mix")
I just copied it from the old code. Updated.

2020-11-17 07:43 UTC, josevalim commented on lib/mix/lib/mix.ex
> +  - `:exit_code` - defines exit code value, defaults to `1`
```suggestion
    * `:exit_code` - defines exit code value, defaults to `1`
```

2020-11-17 07:44 UTC, merged

2020-11-17 07:44 UTC, josevalim commented
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart: