Emit notice logs in :console backend
elixir-lang/elixir pull request #11304
Opened 2021-10-08 12:55 UTC by riccardomanfrin

yes.. this is not very "backward compatible"..
I guess adding some config flag to enable it, and
default it to false.. would be proper (?)

2021-10-08 14:00 UTC, riccardomanfrin commented
I've added support for `:notice` in the `formatter.ex` and changed the `console.ex` backend.. I hope this is limiting the propagation of the `:notice` to only the console backend, leaving the rest of backends happy (the key was there already as `erl_level`)

Is this what you meant?

It's in any case breaking the format of preexisting log collections in case someone was logging to notice.

2021-10-08 14:39 UTC, josevalim commented on lib/logger/lib/logger/backends/console.ex
> +    {:erl_level, level} = List.keyfind(md, :erl_level, 0, :not_found)
```suggestion
    {:erl_level, level} = List.keyfind(md, :erl_level, 0, {:erl_level, :not_found})
```

2021-10-08 14:50 UTC, josevalim commented on lib/logger/lib/logger/backends/console.ex
> +    {:erl_level, level} = List.keyfind(md, :erl_level, 0, {:erl_level, :not_found})
Good find!

2021-10-08 15:22 UTC, josevalim commented on lib/logger/lib/logger/backends/console.ex
> +    end
No, let's not convert back. `Logger.warn` is already deprecated, so it is a good opportunity to move to `warning`. :)

2021-10-08 15:41 UTC, josevalim commented on lib/logger/lib/logger/backends/console.ex
> +      warning: Keyword.get(colors, :warning, :yellow),
```suggestion
      warning: Keyword.get(colors, :warn, :yellow),
```

2021-10-08 19:09 UTC, josevalim commented on lib/logger/test/logger/backends/console_test.exs
> +             IO.ANSI.yellow() <> "hello" <> IO.ANSI.reset()
```suggestion
             IO.ANSI.cyan() <> "hello" <> IO.ANSI.reset()
```

2021-10-09 13:11 UTC, hauleth requested changes
Ignoring all the comments, I have different concept how we can add support for more features from Erlang logger instead.

- add new optional callback for the backends, for example `type/0` that will return `:legacy | :rich` and will default to `:legacy` if not defined
- for `:legacy` backends receives message in the current, tuple based, format
- for `:rich` (can use different name there) backend receives message in "raw" format from the Erlang (possibly with some alterations to wrap `:report_cb` for example)

This approach should give us a way to make full transition in future (possibly still in multiple steps).

What do you think @josevalim about such approach? It would give a way to have smother transition period, and possibly migrate to "new" format even without bumping Logger's major version (which would imply bumping Elixir's major version).

2021-10-09 14:41 UTC, josevalim commented on lib/logger/lib/logger/formatter.ex
> +  # TODO: Deprecate me on Elixir v1.13+ or later
levelpad is not very useful now when one of the levels is "emergency". There will be just too much padding on something like "info" (5 chars to be more precise).

2021-10-09 14:56 UTC, merged

2021-10-09 15:13 UTC, hauleth commented
@josevalim you probably meant #7928. I can see if I can craft something like that as a part of Hacktoberfest.

I wouldn't say that it is strictly needed to get us there, but for sure can ease transition period (unless I really will be able to craft my PR before 1.13).