return the original string if the list of patterns is empty
elixir-lang/elixir pull request #11488
Opened 2021-12-15 04:36 UTC by sushant12

closes #11485

2021-12-15 13:08 UTC, eksperimental requested changes
If we are going this way, it should also be replicated for `String.split/3` which also expects a pattern.

If we Introduce this, I think we should provide a `String.compile_pattern/1` which will deal with versions of pattern that are not handled by `:binary.compile_pattern/1` such as `[]` and `""`.

If we don't introduce this accept these changes, the typespecs for `t:String.pattern/0` needs to be updated to: `t() | nonempty_list(t()) | :binary.cp()`

2021-12-15 14:35 UTC, josevalim commented
Hi @sushant12! Thanks for the PR. Unfortunately we decided to not pursue this direction for now, sorry! See the discussion in #11485 for more info.

2021-12-15 14:38 UTC, sussbuzz commented
followed every discussion :D . Thanks Jose

2021-12-16 07:27 UTC, josevalim commented on lib/elixir/test/elixir/string_test.exs
> +      assert String.replace("elixir", [], "") == "elixir"
```suggestion
      assert String.replace("elixir", [], "anything") == "elixir"
```

2021-12-16 07:37 UTC, merged

2021-12-16 07:37 UTC, josevalim commented
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart: