adds test_pid field in the test metadata
elixir-lang/elixir pull request #13880
Opened 2024-10-05 22:10 UTC by ityonemo

this enhancement adds a `test_pid` field into the test context metadata.  This is useful for backtracking which test is responsible when a ecto sandbox or mox allowance has triggered after the parent test has finished.  For now, one will have to write a custom `ExUnit.Formatter` to take advantage of this extra metadata.

2024-10-06 01:05 UTC, josevalim requested changes
Looks good to me! Please run the formatter and add tests. :)

2024-10-06 07:11 UTC, whatyouhide commented on lib/ex_unit/lib/ex_unit.ex
> +      * `:test_pid` - the pid that the test was running on
```suggestion
      * `:test_pid` - the PID that the test was running on
```

2024-10-16 18:17 UTC, josevalim commented
@ityonemo ping in case it fell through the cracks. :)

2024-11-07 17:16 UTC, axelson commented
@ityonemo I've added a test case at https://github.com/ityonemo/elixir/pull/1

I'd love for this to go through so I can use it to print out richer information about sandbox/allowance failures from a custom ex_unit formatter!

2024-11-07 20:05 UTC, closed without merging

2024-11-07 20:05 UTC, josevalim commented
Thank you @axelson! Looking at the test you added, I think it would be much simpler to test_pid at the beginning, simpler to use and to test too, so I pushed this change. Thank you both!